import type { AppState, EffectiveTask, Mode } from '../domain/types.js';
import { addDays, CATEGORY_LABEL, conflicts, dayTasks, endTime, MODE_LABEL, modeFor, monday, OUTCOME_LABEL } from '../domain/planner.js';
import { categoryIcon, e, fullDate, icon, shortDate } from './html.js';
export type View = 'today' | 'history' | 'templates' | 'settings';
export interface Context { state: AppState; date: string; view: View; child: boolean; warning: string; rawAvailable: boolean }
const nav = [ ['today', 'sun', '今日節奏'], ['history', 'history', '成長回看'], ['templates', 'template', '我的模板'], ['settings', 'settings', '家庭設定'] ];
function navigation(view: View, mobile = false): string {
  return `<nav class="${mobile ? 'mobile-nav' : 'navigation'}" aria-label="${mobile ? '手機主要功能' : '主要功能'}">${nav.map(([key, img, label]) => `<button id="${mobile ? 'm-' : ''}nav-${key}" data-action="navigate" data-view="${key}" ${key === view ? 'aria-current="page"' : ''}>${icon(img!)}<span>${label}</span></button>`).join('')}</nav>`;
}
function dateRail(date: string): string {
  const start = monday(date);
  return `<div class="date-rail"><button class="icon-btn" data-action="week" data-offset="-7" aria-label="上一週">${icon('left')}</button><div class="date-days">${Array.from({ length: 7 }, (_, i) => {
    const d = addDays(start, i); return `<button id="day-${d}" class="date-day ${d === date ? 'selected' : ''}" data-action="date" data-date="${d}" aria-label="${e(fullDate(d))}" aria-pressed="${d === date}"><span>${['一', '二', '三', '四', '五', '六', '日'][i]}</span><strong>${Number(d.slice(8))}</strong><i></i></button>`;
  }).join('')}</div><button class="icon-btn" data-action="week" data-offset="7" aria-label="下一週">${icon('right')}</button></div>`;
}
function nextCard(row: EffectiveTask | undefined, child: boolean): string {
  if (!row) return `<section class="next-card empty-next"><div class="next-kicker">${icon('leaf')} 現在，留一點空間</div><h2>接下來是自己的時間。</h2><p>沒有待進行的小步驟。不需要為了填滿行程再加任務。</p></section>`;
  return `<section class="next-card"><div class="next-kicker">${icon('sparkle')} ${child ? '我的下一小步' : '下一小步'} <span>${e(row.task.start)} · 最多 ${row.minutes} 分鐘</span></div><h2>${e(row.task.title)}</h2><p>${e(row.task.goal || '選一個做得到的小目標，開始就好。')}</p><div class="next-bottom"><button class="btn btn-primary" data-action="record" data-id="${e(row.task.id)}">${child ? '看看怎麼做' : '開始這一小步'} ${icon('arrow')}</button><span>做到這裡就好，不追加新題目</span></div></section>`;
}
function taskCard(row: EffectiveTask, child = false): string {
  const { task, status, minutes } = row; const terminal = ['done', 'rest', 'mode-rest'].includes(status);
  const statusLabel = status === 'done' ? '已完成' : status === 'help' ? '需要幫忙' : status === 'rest' ? '已調整休息' : status === 'mode-rest' ? '本模式休息' : '';
  return `<article class="task-row ${status}" data-task-id="${e(task.id)}"><div class="time-col"><strong>${e(task.start)}</strong><span>${minutes === 0 ? '留白' : e(endTime(task.start, minutes))}</span></div><div class="task-icon ${task.category}">${icon(status === 'done' ? 'check' : categoryIcon(task.category))}</div><div class="task-main"><div class="task-top"><span class="category-label">${CATEGORY_LABEL[task.category]}</span>${!task.flexible ? `<span class="protected">${icon('shield')} 保留</span>` : ''}${statusLabel ? `<span class="status-chip ${status}">${statusLabel}</span>` : ''}</div><h3>${e(task.title)}</h3><p>${e(task.goal)}</p><div class="task-meta">${minutes ? `${minutes} 分鐘上限` : '不移到睡前補做'}${task.target !== null ? ` <span>·</span> 預計 ${task.target} ${e(task.unit)}` : ''}${row.record?.actualMinutes !== null && row.record?.actualMinutes !== undefined ? ` <span>·</span> 實際 ${row.record.actualMinutes} 分` : ''}</div></div><div class="task-actions">${!terminal ? `<button class="icon-btn" data-action="record" data-id="${e(task.id)}" aria-label="記錄：${e(task.title)}">${icon('check')}</button>` : ''}${!child && !['done', 'rest'].includes(status) ? `<button class="icon-btn edit-button" data-action="edit" data-id="${e(task.id)}" aria-label="編輯：${e(task.title)}">${icon('edit')}</button>` : ''}</div></article>`;
}
function today(context: Context): string {
  const { state, date, child } = context; const rows = dayTasks(state, date); const mode = modeFor(state, date);
  const pending = rows.filter(r => r.status === 'pending' || r.status === 'help'); const next = pending[0];
  const done = rows.filter(r => r.status === 'done').length; const rest = rows.filter(r => r.status === 'rest' || r.status === 'mode-rest').length;
  const flexibleMinutes = rows.filter(r => r.task.flexible && r.status !== 'rest').reduce((n, r) => n + r.minutes, 0);
  const issues = conflicts(state, date);
  if (child) return `<div class="child-heading"><span class="eyebrow">一步一步，就很足夠</span><h1>${e(state.profile.childName)}的小步時間</h1><p>${e(fullDate(date))}</p></div>${nextCard(next, true)}<section class="child-follow"><h2>再接下來</h2>${pending.slice(1, 3).map(r => taskCard(r, true)).join('') || '<p class="muted">沒有其他安排，留下自己的空間。</p>'}</section><div class="gentle-note">${icon('leaf')} 累了可以說；休息不是做錯事。</div><p class="prototype-note">示範孩子介面，不是獨立帳號或權限保護。</p>`;
  return `<div class="page-heading"><div><span class="eyebrow">TODAY, AT YOUR OWN PACE</span><h1>今天，走自己的步調。</h1><p>${e(fullDate(date))} <span class="dot-sep">·</span> ${e(state.profile.childName)}的學習安排</p></div><button class="btn btn-primary" data-action="add">${icon('plus')} 新增安排</button></div>
    <div class="date-tools"><span>${e(shortDate(monday(date)))} — ${e(shortDate(addDays(monday(date), 6)))}</span><div><button class="text-btn" data-action="today">回今天</button><label class="date-picker-label">選日期<input id="date-picker" type="date" value="${date}" min="2000-01-01" max="2100-12-31" aria-label="選擇日期"></label></div></div>${dateRail(date)}
    <div class="main-grid"><div class="primary-column">${nextCard(next, false)}
      <section class="timeline"><div class="section-heading"><h2>今天的安排 <span>${rows.length}</span></h2><span class="muted">${done} 項已完成 · ${rest} 項已調整</span></div>
      ${rows.length ? rows.map(r => taskCard(r)).join('') : `<div class="empty-state">${icon('calendar')}<h3>這一天還是空白的</h3><p>新增一個安排，或從「我的模板」帶入一週。</p><button class="btn btn-secondary" data-action="add">新增第一個安排</button></div>`}</section></div>
      <aside class="secondary-column"><section class="panel mode-panel"><div class="section-heading"><h2>今天的步調</h2>${icon('leaf')}</div><p>安排跟著生活調整。</p><div class="mode-options" role="group" aria-label="今日模式">${(['normal', 'compact', 'rest'] as Mode[]).map(m => `<button id="mode-${m}" data-action="mode" data-mode="${m}" aria-pressed="${m === mode}">${icon(m === 'normal' ? 'sun' : m === 'compact' ? 'sparkle' : 'cup')}<span>${MODE_LABEL[m]}</span></button>`).join('')}</div><div class="space-summary"><strong>${flexibleMinutes}<small> 分</small></strong><span>彈性學習的預留上限<br>不是需要完成的配額</span></div><p class="small-note">精簡只縮短可調整活動；休息只停用彈性學習。固定課程、用餐與必做作業不動。</p>${state.changes.some(c => c.date === date && !c.undoneAt) ? `<button class="text-btn undo-mode" data-action="undo-mode">${icon('undo')} 撤銷上次模式調整</button>` : ''}</section>
      <section class="panel goal-panel"><span class="eyebrow">這一週，先做好一件事</span><h3>${e(state.profile.goal || '設定一個小目標')}</h3><p>不比練了多久，先回看哪個地方少了一次提醒。</p><button class="text-btn" data-action="navigate" data-view="settings">調整目標 ${icon('arrow')}</button></section>
      ${issues.length ? `<section class="panel warning-panel" role="status"><h3>${icon('info')} 有 ${issues.length} 個安排需確認</h3><ul>${issues.map(x => `<li>${e(x)}</li>`).join('')}</ul><p>目前只提示衝突，不會擅自重排。</p></section>` : `<section class="gentle-note">${icon('shield')} 目前沒有時段重疊。交通與實際體力仍需自行確認。</section>`}
      <div class="privacy-note">${icon('shield')} 只存在此瀏覽器<br>沒有登入、追蹤或自動上傳</div></aside></div>`;
}
function history({ state }: Context): string {
  const live = state.records.filter(r => !r.voidedAt); const timed = live.filter(r => r.actualMinutes !== null);
  const total = timed.reduce((n, r) => n + r.actualMinutes!, 0);
  return `<div class="page-heading"><div><span class="eyebrow">SMALL STEPS, REAL PROGRESS</span><h1>回看，不是打分數。</h1><p>紀錄真的發生了什麼；改計畫，不改歷史。</p></div></div><div class="metric-strip"><div><strong>${live.filter(r => r.outcome === 'done').length}</strong><span>次完成紀錄</span></div><div><strong>${live.filter(r => r.outcome === 'help').length}</strong><span>次需要幫忙</span></div><div><strong>${total}<small> 分</small></strong><span>已填寫的實際時間 · ${timed.length}筆</span></div></div>
    <section class="panel records-panel"><div class="section-heading"><h2>學習足跡</h2><span class="muted">未計時不當成0分鐘</span></div>${state.records.length ? [...state.records].reverse().map(r => `<article class="record-card ${r.voidedAt ? 'voided' : ''}"><div class="record-head"><span class="category-label">${e(shortDate(r.taskSnapshot.date))} · ${e(r.taskSnapshot.start)} · 原安排 ${r.scheduledMinutes} 分</span><span class="status-chip ${r.voidedAt ? 'rest' : r.outcome}">${r.voidedAt ? '已更正，不計入統計' : OUTCOME_LABEL[r.outcome]}</span></div><h3>${e(r.taskSnapshot.title)}</h3><p>${e(r.observation || '這次沒有加註觀察。')}</p><div class="record-bottom"><span>實際時間：${r.actualMinutes === null ? '未計時' : `${r.actualMinutes} 分`}${r.quantity === null ? '' : ` · 本次份量：${r.quantity} ${e(r.taskSnapshot.unit)}`}</span>${!r.voidedAt ? `<button class="text-btn" data-action="void-record" data-id="${e(r.id)}">更正這筆紀錄</button>` : ''}</div></article>`).join('') : `<div class="empty-state">${icon('leaf')}<h3>還沒有足跡，沒關係。</h3><p>完成一個小步驟，或記下需要幫忙的地方，就會出現在這裡。</p><button class="btn btn-secondary" data-action="navigate" data-view="today">回到今日節奏</button></div>`}</section>
    <section class="panel change-panel"><h2>日程調整紀錄</h2>${state.changes.length ? [...state.changes].reverse().map(c => `<div class="change-row"><span>${e(shortDate(c.date))} · ${MODE_LABEL[c.before]} ${icon('arrow')} ${MODE_LABEL[c.after]}</span><span class="muted">${c.changes.length} 個時段調整${c.undoneAt ? ' · 已撤銷' : ''}</span></div>`).join('') : '<p class="muted">切換模式後，這裡會留下調整摘要。</p>'}</section>`;
}
function templates({ state, date }: Context): string {
  return `<div class="page-heading"><div><span class="eyebrow">START FROM WHAT WORKS</span><h1>不用每週，重新想一次。</h1><p>只複用安排與目標，不複製完成紀錄。</p></div><button class="btn btn-primary" data-action="save-template">${icon('plus')} 儲存這週模板</button></div><div class="info-banner">${icon('info')} 目前選取 ${e(shortDate(monday(date)))} — ${e(shortDate(addDays(monday(date), 6)))}。模板僅能套用至空白週，避免覆寫既有資料。</div>
    <div class="template-grid">${state.templates.length ? state.templates.map(t => `<article class="panel template-card"><div class="template-mark">${icon('template')}</div><span class="eyebrow">家庭週模板</span><h2>${e(t.name)}</h2><p>${t.items.length} 個活動 · 7天模式<br>會建立新的活動識別碼與空白紀錄。</p><button class="btn btn-secondary" data-action="apply-template" data-id="${e(t.id)}">預覽套用 ${icon('arrow')}</button></article>`).join('') : `<div class="panel empty-state">${icon('template')}<h3>從一個做得到的星期開始</h3><p>先調整示範日程，再儲存成自己的第一個模板。</p><button class="btn btn-secondary" data-action="save-template">儲存這週模板</button></div>`}</div>`;
}
function settings({ state, warning, rawAvailable }: Context): string {
  const p = state.profile;
  return `<div class="page-heading"><div><span class="eyebrow">MADE FOR YOUR FAMILY</span><h1>留給你的，調整空間。</h1><p>只需要暱稱，不需要完整生日或學校資料。</p></div></div><div class="settings-grid"><section class="panel"><h2>家庭偏好</h2><form id="profile-form" class="stack-form"><label>孩子暱稱<input name="childName" maxlength="30" value="${e(p.childName)}" required></label><label>這週的小目標<textarea name="goal" rows="3" maxlength="200">${e(p.goal)}</textarea></label><div class="form-grid"><label>一天可用時段・開始<input type="time" name="dayStart" value="${e(p.dayStart)}" required></label><label>一天可用時段・結束<input type="time" name="dayEnd" value="${e(p.dayEnd)}" required></label></div><label>字體大小<select name="fontScale">${[1, 1.1, 1.2].map(n => `<option value="${n}" ${n === p.fontScale ? 'selected' : ''}>${Math.round(n * 100)}%</option>`).join('')}</select></label><button class="btn btn-primary" type="submit">儲存偏好 ${icon('check')}</button></form></section><div><section class="panel"><h2>資料在你手上</h2><p class="muted">僅儲存在目前瀏覽器。換裝置、清除瀏覽資料或移動HTML檔案，都可能無法讀到原本紀錄，請先備份。</p><div class="stack-actions"><button class="btn btn-secondary" data-action="export">${icon('download')} 匯出陪步備份</button><button class="btn btn-secondary" data-action="import">${icon('upload')} 匯入陪步備份</button><button class="btn btn-secondary" data-action="print">${icon('calendar')} 列印目前選取的一天</button>${rawAvailable && warning ? '<button class="btn btn-secondary" data-action="export-raw">匯出未修改的原始資料</button>' : ''}</div><p class="small-note">僅支援陪步 v1 JSON，最大1 MB。舊版四天連假HTML的備份格式不同，不會自動匯入。</p></section><section class="panel scope-panel"><span class="eyebrow">PROTOTYPE · 0.1.0</span><h3>這一版的界線</h3><p>家長／孩子切換是介面展示，不是帳號權限。沒有雲端同步、AI評分、通知或行事曆整合。</p><p>示範暱稱、目標與活動均為虛構。請先用示範資料體驗，不要填入敏感個資。</p><p>可用時間只做衝突提示，不會自動更動老師課程或保證安排可行。</p></section></div></div>`;
}
export function renderApp(context: Context): string {
  const { state, date, view, child, warning } = context;
  const body = child ? today(context) : view === 'today' ? today(context) : view === 'history' ? history(context) : view === 'templates' ? templates(context) : settings(context);
  return `<a class="skip-link" href="#main-content">跳到主要內容</a><div class="app-shell ${child ? 'child-shell' : ''}"><aside class="sidebar"><a class="brand" href="#" data-action="home"><span class="brand-symbol"><i></i><i></i></span><span>陪步 <small>PEIBU</small></span></a><div class="workspace-tag"><span class="avatar">${e(Array.from(state.profile.childName)[0] ?? "家")}</span><div>我的家庭空間<small>LOCAL PROTOTYPE</small></div></div>${child ? '' : navigation(view)}<div class="sidebar-bottom"><div class="little-path"><i></i><i></i><i></i></div><strong>一步就好，<br>剩下的慢慢來。</strong><span>規劃不是填滿每一分鐘。</span><span class="version">v0.1.0 · 虛構示範資料</span></div></aside><div class="workspace"><header class="topbar"><a href="#" class="mobile-brand" data-action="home">陪步<span>PEIBU</span></a><span class="breadcrumb">家庭空間 <span>/</span> ${child ? '孩子視圖' : nav.find(n => n[0] === view)?.[2]}</span><div class="topbar-actions"><span class="save-badge ${warning ? 'unsaved' : ''}"><i></i>${warning ? '暫存・尚未保存' : '已存於此瀏覽器'}</span><div class="role-switch" role="group" aria-label="切換介面"><button id="parent-mode" data-action="role" data-role="parent" aria-pressed="${!child}">家長</button><button id="child-mode" data-action="role" data-role="child" aria-pressed="${child}">孩子</button></div></div></header>${warning ? `<div class="storage-alert" role="alert">${e(warning)} <button class="text-btn" data-action="export">匯出本頁備份</button></div>` : ''}<main id="main-content" tabindex="-1">${body}</main><footer class="app-footer"><span>陪步 · 讓安排跟著生活走</span><span>本機原型 · 不自動傳送資料</span></footer></div>${child ? '' : navigation(view, true)}</div><input id="import-file" type="file" accept=".json,application/json" hidden><div id="dialog-root"></div><div id="toast" class="toast" role="status" aria-live="polite"></div><div class="print-content"><h1>${e(state.profile.childName)}的一天</h1><p>${e(fullDate(date))} · ${MODE_LABEL[modeFor(state, date)]}模式</p>${dayTasks(state, date).map(r => `<p>□ ${e(r.task.start)} · ${e(r.task.title)} · ${r.status === 'mode-rest' ? '休息' : `${r.minutes}分上限`}<br><small>${e(r.task.goal)}</small></p>`).join('')}<p>留白不補課。這是安排，不是時數配額。</p></div>`;
}
